calliostro_spotify_web_api:

  # Your Client ID
  client_id: 'a70dcab0ce0c4b79980456b40ee514a8'

  # Your Client Secret
  client_secret: '74f389fb7c2b4370af050161a11b0e43'

  # Options for SpotifyWebAPI client
  # https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/examples/setting-options.md
  options:
    auto_refresh: false
    auto_retry: false
    return_assoc: false

  # Address to redirect to after authentication success OR failure
  redirect_uri: 'http://127.0.0.1:8099/spotify/auth/callback'

  # Service ID of the token provider that provides the user's access token
  token_provider: calliostro_spotify_web_api.token_provider